filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["192.168.229.143:9200"]
  protocol: "http"

setup.kibana:
  host: "192.168.229.143:5601"
