filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    fields:
      module: wazuh

output.elasticsearch:
  hosts: ["192.168.229.143:9200"]
  index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"
  allow_older_versions: true

setup.ilm.enabled: false
setup.template.enabled: false
