filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/ossec/logs/alerts/alerts.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true

setup.template.settings:
  index.number_of_shards: 1

setup.template.name: "wazuh"
setup.template.pattern: "wazuh-alerts-*"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["192.168.229.143:9200"]
  protocol: "http"
  index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"

setup.kibana:
  host: "192.168.229.143:5601"
